-- INSERT statements for Clinical-Adjacent credentials
-- Healthcare administration, informatics, coding, compliance, revenue cycle,
-- sterile processing, biomedical technology, and related non-clinical professional credentials

INSERT INTO dctnry.clinical_credential
  (id, credential_abbr, unique_credential_abbr, credential_name, credentialing_organization_name,
   credentialing_organization_url, credential_description, is_multisource, is_clinical,
   is_board_certification, is_credential_retired, is_fhir_credential, duplicate_abbreviation_code, created_at, updated_at, credential_class)
VALUES

  -- Health Informatics and Information Management
  (70000, 'ACHIP', 'ACHIP', 'AMIA Certified Health Informatics Professional', 'American Medical Informatics Association', 'https://amia.org/careers-certifications-informatics/amia-health-informatics-certification-ahic', 'Professional certification in health informatics issued by AMIA, demonstrating competency in clinical and health information systems.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70000
  (70001, 'CAHIMS', 'CAHIMS', 'Certified Associate in Healthcare Information and Management Systems', 'HIMSS', 'https://www.himss.org/certifications/', 'Entry-level HIMSS certification for professionals working in health information and management systems.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70001
  (70002, 'CPHIMS', 'CPHIMS', 'Certified Professional in Healthcare Information and Management Systems', 'HIMSS', 'https://www.himss.org/certifications/cphims/', 'Advanced HIMSS certification demonstrating expertise in healthcare information and management systems.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70002
  (70003, 'CPDHTS', 'CPDHTS', 'Certified Professional in Digital Health Transformation Strategy', 'HIMSS', 'https://www.himss.org/certifications/', 'HIMSS certification for professionals leading digital health transformation initiatives in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70003
  (70004, 'RHIA', 'RHIA', 'Registered Health Information Administrator', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA credential for health information management professionals responsible for overseeing patient health information and medical records.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70004
  (70005, 'RHIT', 'RHIT', 'Registered Health Information Technician', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA credential for health information technicians who process, manage, and protect patient health information.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70005
  (70006, 'CHDA', 'CHDA', 'Certified Health Data Analyst', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA certification for professionals who acquire, manage, analyze, interpret, and transform health data into accurate and consistent information.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70006
  (70007, 'CDIP', 'CDIP', 'Certified Documentation Integrity Practitioner', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA certification for professionals who work to improve the quality and completeness of clinical documentation in healthcare settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70007
  (70008, 'CHPS', 'CHPS', 'Certified in Healthcare Privacy and Security', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA certification demonstrating expertise in designing, implementing, and administering comprehensive privacy and security programs.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70008
  (70009, 'FAHIMA', 'FAHIMA', 'Fellow of the American Health Information Management Association', 'AHIMA', 'https://ahima.org/who-we-are/fellowship/', 'Honorary AHIMA fellowship recognizing outstanding contributions to the health information management profession.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'Health Informatics and Information Management'), -- 70009

  -- Medical Coding Credentials (AHIMA)
  (70010, 'CCA', 'CCA', 'Certified Coding Associate', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'Entry-level AHIMA coding credential for professionals beginning their career in medical coding.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AHIMA)'), -- 70010
  (70011, 'CCS', 'CCS', 'Certified Coding Specialist', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA credential for coding specialists demonstrating expertise in hospital-based inpatient and outpatient coding.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AHIMA)'), -- 70011
  (70012, 'CCS-P', 'CCS-P', 'Certified Coding Specialist - Physician Based', 'AHIMA', 'https://www.ahima.org/certification-careers/apply/', 'AHIMA credential for coding specialists with expertise in physician-based settings and outpatient coding.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AHIMA)'), -- 70012

  -- Medical Coding Credentials (AAPC)
  (70013, 'CPC', 'CPC (nc)', 'Certified Professional Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC flagship coding credential for professional coders working in physician office and outpatient settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70013
  (70014, 'COC', 'COC', 'Certified Outpatient Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for coders specializing in hospital outpatient and ambulatory surgery coding.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70014
  (70015, 'CIC', 'CIC (nc)', 'Certified Inpatient Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for coders specializing in hospital inpatient coding. Distinct from the clinical Certified in Infection Control credential.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70015
  (70016, 'CPB', 'CPB', 'Certified Professional Biller', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for medical billing professionals demonstrating expertise in healthcare billing and reimbursement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70016
  (70017, 'CPMA', 'CPMA', 'Certified Professional Medical Auditor', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for professionals who audit medical records and coding for compliance and accuracy.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70017
  (70018, 'CPCO', 'CPCO', 'Certified Professional Compliance Officer', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for healthcare compliance officers overseeing regulatory and coding compliance programs.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70018
  (70019, 'CPPM', 'CPPM', 'Certified Physician Practice Manager', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for professionals managing physician practice operations, billing, and compliance.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70019
  (70020, 'CRC', 'CRC', 'Certified Risk Adjustment Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC credential for coders specializing in risk adjustment coding under value-based payment models.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70020
  (70021, 'CANPC', 'CANPC', 'Certified Anesthesia and Pain Management Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for professionals coding anesthesia and pain management services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70021
  (70022, 'CASCC', 'CASCC', 'Certified Ambulatory Surgery Center Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for professionals working in ambulatory surgery center coding and billing.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70022
  (70023, 'CCC', 'CCC', 'Certified Cardiology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in cardiology procedures and services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70023
  (70024, 'CCVTC', 'CCVTC', 'Certified Cardiovascular and Thoracic Surgery Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders working in cardiovascular and thoracic surgery services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70024
  (70025, 'CEDC', 'CEDC', 'Certified Emergency Department Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in emergency department services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70025
  (70026, 'CEMC', 'CEMC', 'Certified Evaluation and Management Coder', 'AAPC', 'https://www.aapc.com/certifications/cemc', 'AAPC credential for coders specializing in evaluation and management coding guidelines and documentation requirements.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70026
  (70027, 'CFPC', 'CFPC', 'Certified Family Practice Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders working in family practice and primary care settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70027
  (70028, 'CGIC', 'CGIC', 'Certified Gastroenterology Coder', 'AAPC', 'https://www.aapc.com/certifications/cgic', 'AAPC specialty coding credential for coders specializing in gastroenterology procedures and services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70028
  (70029, 'CGSC', 'CGSC', 'Certified General Surgery Coder', 'AAPC', 'https://www.aapc.com/certifications/cgsc', 'AAPC specialty coding credential for coders specializing in general surgery procedures and services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70029
  (70030, 'CHONC', 'CHONC', 'Certified Hematology and Oncology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders working in hematology and oncology practices.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70030
  (70031, 'CIRCC', 'CIRCC', 'Certified Interventional Radiology Cardiovascular Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in interventional radiology and cardiovascular coding.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70031
  (70032, 'COBGC', 'COBGC', 'Certified Obstetrics Gynecology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in obstetrics and gynecology services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70032
  (70033, 'COPC', 'COPC', 'Certified Ophthalmology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders working in ophthalmology practices and eye care services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70033
  (70034, 'COSC', 'COSC', 'Certified Orthopaedic Surgery Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in orthopaedic surgery procedures and services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70034
  (70035, 'CPCD', 'CPCD', 'Certified Professional Coder in Dermatology', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in dermatology services and procedures.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70035
  (70036, 'CPEDC', 'CPEDC', 'Certified Pediatrics Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in pediatric services and procedures.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70036
  (70037, 'CRHC', 'CRHC', 'Certified Rheumatology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in rheumatology services and procedures.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70037
  (70038, 'CUC', 'CUC', 'Certified Urology Coder', 'AAPC', 'https://www.aapc.com/add-aapc-certification-to-linkedin.aspx', 'AAPC specialty coding credential for coders specializing in urology services and procedures.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70038
  (70039, 'CDEI', 'CDEI', 'Certified Documentation Expert Inpatient', 'AAPC', 'https://www.aapc.com/certifications/cdei', 'AAPC credential for documentation experts specializing in inpatient clinical documentation improvement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70039
  (70040, 'CDEO', 'CDEO', 'Certified Documentation Expert Outpatient', 'AAPC', 'https://www.aapc.com/certifications/cdeo', 'AAPC credential for documentation experts specializing in outpatient clinical documentation improvement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70040
  (70041, 'CPMS', 'CPMS', 'Certified Professional Medical Scribe', 'AAPC', 'https://www.aapc.com/education/exam-preparation/cpms-exam-preparation-course', 'AAPC credential for medical scribes who assist clinicians with real-time clinical documentation during patient encounters.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Coding Credentials (AAPC)'), -- 70041

  -- Clinical Documentation Improvement (ACDIS)
  (70042, 'CCDS', 'CCDS', 'Certified Clinical Documentation Specialist', 'Association of Clinical Documentation Integrity Specialists', 'https://acdis.org/certification/certifications-certificates-faqs', 'ACDIS credential for clinical documentation improvement specialists working in inpatient hospital settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Clinical Documentation Improvement (ACDIS)'), -- 70042
  (70043, 'CCDS-O', 'CCDS-O', 'Certified Clinical Documentation Specialist - Outpatient', 'Association of Clinical Documentation Integrity Specialists', 'https://acdis.org/certification/ccds-o', 'ACDIS credential for clinical documentation improvement specialists working in outpatient settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Clinical Documentation Improvement (ACDIS)'), -- 70043

  -- Healthcare Compliance (HCCA)
  (70044, 'CHC', 'CHC_1', 'Certified in Healthcare Compliance', 'Health Care Compliance Association', 'https://www.hcca-info.org/certification/about-certification', 'HCCA credential for healthcare compliance professionals demonstrating expertise in regulatory compliance program development and management.', FALSE, FALSE, TRUE, FALSE, FALSE, 3, NULL, NULL, 'Healthcare Compliance (HCCA)'), -- 70044
  (70045, 'CHC-F', 'CHC-F', 'Certified in Healthcare Compliance - Fellow', 'Health Care Compliance Association', 'https://www.hcca-info.org/membership/membership-benefits/membership', 'HCCA fellowship-level designation for senior healthcare compliance professionals with demonstrated leadership in the field.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Compliance (HCCA)'), -- 70045
  (70046, 'CHPC', 'CHPC', 'Certified in Healthcare Privacy Compliance', 'Health Care Compliance Association', 'https://www.hcca-info.org/certification/about-certification', 'HCCA credential for professionals specializing in healthcare privacy compliance and HIPAA program management.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Compliance (HCCA)'), -- 70046
  (70047, 'CHRC', 'CHRC', 'Certified in Healthcare Research Compliance', 'Health Care Compliance Association', 'https://www.hcca-info.org/certification/about-certification', 'HCCA credential for compliance professionals specializing in research compliance in academic medical and research institutions.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Compliance (HCCA)'), -- 70047

  -- AHA Facility Management and Safety
  (70048, 'CHC', 'CHC_2', 'Certified Health Care Constructor', 'American Hospital Association', 'https://www.aha.org/career-resources/certification-center/chc', 'AHA credential for construction professionals specializing in healthcare facility construction, renovation, and compliance with healthcare building standards.', FALSE, FALSE, TRUE, FALSE, FALSE, 3, NULL, NULL, 'AHA Facility Management and Safety'), -- 70048
  (70049, 'CHESP', 'CHESP', 'Certified Health Care Environmental Services Professional', 'American Hospital Association', 'https://www.aha.org/career-resources/certification-center/chesp', 'AHA credential for environmental services professionals responsible for cleanliness, sanitation, and infection prevention in healthcare facilities.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AHA Facility Management and Safety'), -- 70049
  (70050, 'CHFM', 'CHFM', 'Certified Health Care Facility Manager', 'American Hospital Association', 'https://www.aha.org/career-resources/certification-center/chfm', 'AHA credential for professionals managing healthcare facility operations, physical plant, and regulatory compliance.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AHA Facility Management and Safety'), -- 70050
  (70051, 'CMRP', 'CMRP', 'Certified Materials and Resource Professional', 'American Hospital Association', 'https://www.aha.org/career-resources/certification-center/cmrp', 'AHA credential for supply chain and materials management professionals in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AHA Facility Management and Safety'), -- 70051
  (70052, 'CPHRM', 'CPHRM (nc)', 'Certified Professional in Health Care Risk Management', 'American Hospital Association', 'https://www.aha.org/career-resources/certification-center/cphrm', 'AHA credential for healthcare risk management professionals. Distinct from the clinical nursing credential with the same abbreviation.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AHA Facility Management and Safety'), -- 70052
  (70053, 'MECH', 'MECH', 'Mechanic Evaluation and Certification for Health Care', 'American Hospital Association', 'https://www.aha.org/type/certifications', 'AHA credential for mechanics and maintenance technicians working in healthcare facility environments.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AHA Facility Management and Safety'), -- 70053

  -- HFMA Revenue Cycle and Finance
  (70054, 'CHFP', 'CHFP', 'Certified Healthcare Financial Professional', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA credential for healthcare financial management professionals demonstrating expertise in healthcare finance, accounting, and reimbursement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70054
  (70055, 'CRCR', 'CRCR', 'Certified Revenue Cycle Representative', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA foundational credential for revenue cycle professionals in patient access, billing, and collections.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70055
  (70056, 'CHCRS', 'CHCRS', 'Certified Hospital Cost Report Specialist', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA credential for specialists in Medicare and Medicaid cost report preparation, filing, and settlement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70056
  (70057, 'CSAF', 'CSAF', 'Certified Specialist Accounting and Finance', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA specialty credential for healthcare finance professionals specializing in accounting and financial reporting.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70057
  (70058, 'CSAPM', 'CSAPM', 'Certified Specialist Ambulatory Practice Management', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA specialty credential for finance professionals working in ambulatory and physician practice settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70058
  (70059, 'CSBI', 'CSBI', 'Certified Specialist Business Intelligence', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA specialty credential for professionals using data analytics and business intelligence in healthcare finance.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70059
  (70060, 'CSPPM', 'CSPPM', 'Certified Specialist Physician Practice Management', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA specialty credential for finance professionals specializing in physician practice financial management.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70060
  (70061, 'CSPR', 'CSPR', 'Certified Specialist Payment and Reimbursement', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA specialty credential for professionals specializing in healthcare payment policy and reimbursement systems.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70061
  (70062, 'EHRC', 'EHRC', 'Executive of Healthcare Revenue Cycle', 'Healthcare Financial Management Association', 'https://www.hfma.org/hfma-recognizes-2637-members-who-earned-certifications-in-q4-2024/', 'HFMA executive-level credential for senior revenue cycle leaders responsible for end-to-end revenue cycle strategy.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70062
  (70063, 'FHFMA', 'FHFMA', 'Fellow of the Healthcare Financial Management Association', 'Healthcare Financial Management Association', 'https://www.hfma.org/fellow-of-the-hfma/', 'Honorary HFMA fellowship recognizing outstanding contributions and leadership in healthcare financial management.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'HFMA Revenue Cycle and Finance'), -- 70063

  -- AAHAM Revenue Cycle
  (70064, 'CCT', 'CCT', 'Certified Compliance Technician', 'American Association of Healthcare Administrative Management', 'https://aaham.org/page/Certification', 'AAHAM entry-level credential for revenue cycle professionals demonstrating foundational knowledge of compliance and billing.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AAHAM Revenue Cycle'), -- 70064
  (70065, 'CRCS', 'CRCS', 'Certified Revenue Cycle Specialist', 'American Association of Healthcare Administrative Management', 'https://aaham.org/page/CRCS', 'AAHAM credential for revenue cycle specialists with expertise in billing, collections, and claims management.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AAHAM Revenue Cycle'), -- 70065
  (70066, 'CRCP', 'CRCP', 'Certified Revenue Cycle Professional', 'American Association of Healthcare Administrative Management', 'https://aaham.org/page/CRCP', 'AAHAM advanced credential for revenue cycle professionals with comprehensive expertise in healthcare reimbursement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AAHAM Revenue Cycle'), -- 70066
  (70067, 'CRCE', 'CRCE', 'Certified Revenue Cycle Executive', 'American Association of Healthcare Administrative Management', 'https://aaham.org/page/Certification', 'AAHAM executive-level credential for senior leaders overseeing revenue cycle operations and strategy.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AAHAM Revenue Cycle'), -- 70067
  (70068, 'CRIP', 'CRIP', 'Certified Revenue Integrity Professional', 'American Association of Healthcare Administrative Management', 'https://aaham.org/page/CRIP', 'AAHAM credential for professionals focused on revenue integrity, charge capture accuracy, and billing compliance.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'AAHAM Revenue Cycle'), -- 70068

  -- NAHAM Patient Access
  (70069, 'CHAA', 'CHAA', 'Certified Healthcare Access Associate', 'National Association of Healthcare Access Management', 'https://www.naham.org/', 'NAHAM entry-level credential for patient access professionals in registration, scheduling, and insurance verification.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'NAHAM Patient Access'), -- 70069
  (70070, 'CHAM', 'CHAM', 'Certified Healthcare Access Manager', 'National Association of Healthcare Access Management', 'https://www.naham.org/page/CHAM', 'NAHAM advanced credential for patient access managers overseeing registration, scheduling, and financial clearance operations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'NAHAM Patient Access'), -- 70070

  -- NAMSS Credentialing
  (70071, 'CPCS', 'CPCS', 'Certified Provider Credentialing Specialist', 'National Association Medical Staff Services', 'https://www.namss.org/Certification/NCCA-Accreditation', 'NAMSS credential for professionals who verify and maintain the credentials, privileges, and licensure of healthcare providers.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'NAMSS Credentialing'), -- 70071
  (70072, 'CPMSM', 'CPMSM', 'Certified Professional Medical Services Management', 'National Association Medical Staff Services', 'https://www.namss.org/Certification/NCCA-Accreditation', 'NAMSS advanced credential for medical staff services professionals managing credentialing and privileging programs.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'NAMSS Credentialing'), -- 70072
  (70073, 'CPES', 'CPES', 'Certified Provider Enrollment Specialist', 'National Association Medical Staff Services', 'https://www.namss.org/Certification/Why-Get-Certified', 'NAMSS credential for professionals specializing in provider enrollment with Medicare, Medicaid, and commercial payers.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'NAMSS Credentialing'), -- 70073

  -- CHIME Digital Health Leadership
  (70074, 'CHCIO', 'CHCIO', 'Certified Healthcare CIO', 'College of Healthcare Information Management Executives', 'https://www.credly.com/org/chime/badge/certified-healthcare-cio', 'CHIME credential for chief information officers demonstrating leadership excellence in healthcare information technology.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70074
  (70075, 'CDH-E', 'CDH-E', 'Certified Digital Health Executive', 'College of Healthcare Information Management Executives', 'https://www.credly.com/org/chime/badge/certified-digital-health-executive', 'CHIME executive-level digital health credential for senior healthcare technology leaders.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70075
  (70076, 'CDH-L', 'CDH-L', 'Certified Digital Health Leader', 'College of Healthcare Information Management Executives', 'https://www.credly.com/org/chime/badge/certified-digital-health-leader', 'CHIME leadership-level digital health credential for experienced healthcare technology managers.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70076
  (70077, 'CDH-P', 'CDH-P', 'Certified Digital Health Professional', 'College of Healthcare Information Management Executives', 'https://www.credly.com/org/chime/badge/certified-digital-health-professional', 'CHIME foundational digital health credential for healthcare technology professionals.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70077
  (70078, 'CHISL', 'CHISL', 'Certified Healthcare Information Security Leader', 'College of Healthcare Information Management Executives', 'https://www.credly.com/org/chime/badge/certified-healthcare-information-security-leader', 'CHIME credential for healthcare information security leaders responsible for cybersecurity strategy and governance.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70078
  (70079, 'CFCHE', 'CFCHE', 'CHIME Foundation Certified Healthcare Executive', 'College of Healthcare Information Management Executives', 'https://communications.chimecentral.org/chime-2025-innovation-virtual-summit', 'CHIME Foundation credential for healthcare executives demonstrating proficiency in digital health strategy and leadership.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'CHIME Digital Health Leadership'), -- 70079

  -- Healthcare Executive Leadership (ACHE / MGMA)
  (70080, 'FACHE', 'FACHE', 'Fellow of the American College of Healthcare Executives', 'American College of Healthcare Executives', 'https://www.ache.org/FACHE-Credential', 'ACHE fellowship credential for healthcare executives demonstrating excellence in management, ethics, and lifelong learning.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Executive Leadership (ACHE / MGMA)'), -- 70080
  (70081, 'CMPE', 'CMPE', 'Certified Medical Practice Executive', 'Medical Group Management Association', 'https://www.mgma.com/certification', 'MGMA certification for medical practice executives demonstrating expertise in physician practice management and operations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Executive Leadership (ACHE / MGMA)'), -- 70081
  (70082, 'FACMPE', 'FACMPE', 'Fellow in the American College of Medical Practice Executives', 'Medical Group Management Association', 'https://www.mgma.com/fellowship', 'MGMA fellowship for senior medical practice executives demonstrating distinguished achievement in the profession.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Executive Leadership (ACHE / MGMA)'), -- 70082

  -- Healthcare Quality and Patient Safety
  (70083, 'CPHQ', 'CPHQ (nc)', 'Certified Professional in Healthcare Quality', 'National Association for Healthcare Quality', 'https://nahq.org/news-media/news/the-national-association-for-healthcare-quality-nahq-celebrates-40th-anniversary-of-the-certified-professional-in-healthcare-quality-cphq/', 'NAHQ certification for healthcare quality professionals. Distinct from the clinical nursing CPHQ credential.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Quality and Patient Safety'), -- 70083
  (70084, 'CHCQM', 'CHCQM', 'Certified in Health Care Quality and Management', 'American Board of Quality Assurance and Utilization Review Physicians', 'https://www.abqaurp.org/ABQMain/Exam_Process.aspx', 'ABQAURP interdisciplinary certification for professionals in utilization review, case management, and quality improvement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Quality and Patient Safety'), -- 70084
  (70085, 'CPPS', 'CPPS', 'Certified Professional in Patient Safety', 'Institute for Healthcare Improvement', 'https://www.ihi.org/learn/certifications/cpps', 'IHI certification for professionals committed to advancing patient safety science and practice in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Quality and Patient Safety'), -- 70085
  (70086, 'CPXP', 'CPXP', 'Certified Patient Experience Professional', 'The Beryl Institute', 'https://theberylinstitute.org/credentialing-center-overview/', 'Beryl Institute credential for professionals focused on improving patient and family experience in healthcare settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Quality and Patient Safety'), -- 70086
  (70087, 'CAVS', 'CAVS', 'Certified Administrator of Volunteer Services', 'The Beryl Institute', 'https://theberylinstitute.org/credentialing-center-overview/', 'Beryl Institute credential for professionals managing volunteer programs in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Quality and Patient Safety'), -- 70087

  -- Healthcare Safety (IBFCSM)
  (70088, 'CHSP', 'CHSP', 'Certified Healthcare Safety Professional', 'International Board for Certification of Safety Managers', 'https://ibfcsm.com/certified-healthcare-safety-professional/', 'IBFCSM credential for safety professionals responsible for environment of care, life safety, and emergency management in healthcare facilities.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Safety (IBFCSM)'), -- 70088
  (70089, 'CHEP', 'CHEP', 'Certified Healthcare Emergency Professional', 'International Board for Certification of Safety Managers', 'https://ibfcsm.com/what-is-the-chep-certification-and-who-needs-it/', 'IBFCSM credential for professionals specializing in healthcare emergency management and disaster preparedness.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Safety (IBFCSM)'), -- 70089
  (70090, 'CHFSP', 'CHFSP', 'Certified Healthcare Fire Safety Professional', 'International Board for Certification of Safety Managers', 'https://ibfcsm.com/', 'IBFCSM credential for professionals specializing in fire safety and life safety compliance in healthcare facilities.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Safety (IBFCSM)'), -- 70090
  (70091, 'CHS-EVS', 'CHS-EVS', 'Certified Healthcare Safety - Environmental Services', 'International Board for Certification of Safety Managers', 'https://ibfcsm.com/', 'IBFCSM credential for environmental services professionals with demonstrated competency in healthcare safety standards.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Safety (IBFCSM)'), -- 70091
  (70092, 'CPSO', 'CPSO', 'Certified Patient Safety Officer', 'International Board for Certification of Safety Managers', 'https://ibfcsm.com/', 'IBFCSM credential for patient safety officers responsible for implementing and overseeing patient safety programs.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Safety (IBFCSM)'), -- 70092

  -- Biomedical Technology (AAMI)
  (70093, 'CABT', 'CABT', 'Certified Associate in Biomedical Technology', 'Association for the Advancement of Medical Instrumentation', 'https://aami.org/certifications/cabt/', 'AAMI entry-level credential for biomedical equipment technicians demonstrating foundational knowledge of medical device maintenance and safety.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Biomedical Technology (AAMI)'), -- 70093
  (70094, 'CBET', 'CBET', 'Certified Biomedical Equipment Technician', 'Association for the Advancement of Medical Instrumentation', 'https://aami.org/certifications/cbet/', 'AAMI credential for biomedical equipment technicians who inspect, repair, and maintain medical devices and equipment.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Biomedical Technology (AAMI)'), -- 70094
  (70095, 'CRES', 'CRES', 'Certified Radiology Equipment Specialist', 'Association for the Advancement of Medical Instrumentation', 'https://aami.org/certifications/cres/', 'AAMI credential for technicians specializing in the maintenance and repair of radiology and imaging equipment.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Biomedical Technology (AAMI)'), -- 70095
  (70096, 'CHTM', 'CHTM', 'Certified Healthcare Technology Manager', 'Association for the Advancement of Medical Instrumentation', 'https://aami.org/certifications/chtm/', 'AAMI credential for managers overseeing biomedical engineering and healthcare technology management programs.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Biomedical Technology (AAMI)'), -- 70096
  (70097, 'CISS', 'CISS', 'Certified Industrial Sterilization Specialist', 'Association for the Advancement of Medical Instrumentation', 'https://aami.org/certifications/ciss/', 'AAMI credential for professionals specializing in industrial sterilization processes used in medical device manufacturing.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Biomedical Technology (AAMI)'), -- 70097

  -- Sterile Processing (HSPA)
  (70098, 'CRCST', 'CRCST', 'Certified Registered Central Service Technician', 'Healthcare Sterile Processing Association', 'https://myhspa.org/certification/certification-overview/certified-registered-central-service-technician-crcst/', 'HSPA credential for sterile processing technicians who decontaminate, inspect, assemble, and sterilize reusable medical instruments.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Sterile Processing (HSPA)'), -- 70098
  (70099, 'CHL', 'CHL', 'Certified Healthcare Leader', 'Healthcare Sterile Processing Association', 'https://myhspa.org/certification/certification-overview/certified-healthcare-leader-chl/', 'HSPA credential for supervisors and managers leading sterile processing and central service departments.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Sterile Processing (HSPA)'), -- 70099
  (70100, 'CIS', 'CIS', 'Certified Instrument Specialist', 'Healthcare Sterile Processing Association', 'https://myhspa.org/certification/program-policies/certification-program-use-of-credentials/', 'HSPA credential for sterile processing professionals specializing in surgical instrument management and care.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Sterile Processing (HSPA)'), -- 70100
  (70101, 'CCSVP', 'CCSVP', 'Certified Central Service Vendor Partner', 'Healthcare Sterile Processing Association', 'https://myhspa.org/certification/program-policies/certification-program-use-of-credentials/', 'HSPA credential for vendor partners demonstrating expertise in sterile processing products and services.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Sterile Processing (HSPA)'), -- 70101
  (70102, 'CER', 'CER (nc)', 'Certified Endoscope Reprocessor', 'Healthcare Sterile Processing Association', 'https://myhspa.org/certification/program-policies/certification-program-use-of-credentials/', 'HSPA credential for technicians specializing in endoscope reprocessing, high-level disinfection, and sterilization. Distinct from the FHIR Certificate credential with the same abbreviation.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Sterile Processing (HSPA)'), -- 70102

  -- Health Information Security (ISC2)
  (70103, 'CISSP', 'CISSP', 'Certified Information Systems Security Professional', 'ISC2', 'https://www.isc2.org/certifications/cissp/cissp-certification-exam-outline', 'ISC2 advanced credential for information security professionals demonstrating expertise across multiple security domains including healthcare IT.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Information Security (ISC2)'), -- 70103
  (70104, 'HCISPP', 'HCISPP', 'HealthCare Information Security and Privacy Practitioner', 'ISC2', 'https://www.isc2.org/Certifications/HCISPP', 'ISC2 certification for professionals who implement, manage, and assess security and privacy controls in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Information Security (ISC2)'), -- 70104

  -- HITRUST
  (70105, 'CCSFP', 'CCSFP', 'HITRUST Certified CSF Practitioner', 'HITRUST Alliance', 'https://hitrustalliance.net/ccsfp', 'HITRUST credential for professionals who implement and assess the HITRUST Common Security Framework in healthcare organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'HITRUST'), -- 70105

  -- Healthcare Administration and Medical Management (PMI-MD / PAHCOM)
  (70106, 'CMC', 'CMC (nc)', 'Certified Medical Coder', 'Practice Management Institute', 'https://www.pmimd.com/about/default.php', 'PMI certification for medical coders demonstrating proficiency in coding for physician practices. Distinct from the clinical Cardiac Medicine nursing credential.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70106
  (70107, 'CMCA-E/M', 'CMCA-E/M', 'Certified Medical Chart Auditor E/M', 'Practice Management Institute', 'https://info.pmimd.com/certified-medical-chart-auditor', 'PMI credential for professionals who audit evaluation and management documentation for compliance and accuracy.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70107
  (70108, 'CMCO', 'CMCO', 'Certified Medical Compliance Officer', 'Practice Management Institute', 'https://info.pmimd.com/certified-medical-compliance-officer', 'PMI credential for compliance officers in physician practices responsible for regulatory adherence and risk management.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70108
  (70109, 'CMIS', 'CMIS', 'Certified Medical Insurance Specialist', 'Practice Management Institute', 'https://info.pmimd.com/certified-medical-insurance-specialist', 'PMI credential for professionals specializing in medical insurance billing, verification, and claims processing.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70109
  (70110, 'CMOM', 'CMOM', 'Certified Medical Office Manager', 'Practice Management Institute', 'https://info.pmimd.com/certified-medical-office-manager', 'PMI credential for medical office managers overseeing day-to-day operations of physician practices.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70110
  (70111, 'CMM', 'CMM', 'Certified Medical Manager', 'Professional Association of Health Care Office Management', 'https://www.my.pahcom.com/cmm', 'PAHCOM credential for medical practice managers demonstrating expertise in practice administration and management.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70111
  (70112, 'HITCM-PP', 'HITCM-PP', 'Health Information Technology Certified Manager for Physician Practice', 'Professional Association of Health Care Office Management', 'https://www.my.pahcom.com/hit', 'PAHCOM credential for managers demonstrating proficiency in health information technology applications in physician practices.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Administration and Medical Management (PMI-MD / PAHCOM)'), -- 70112

  -- Medical Billing and Administrative (NHA)
  (70113, 'CBCS', 'CBCS', 'Certified Billing and Coding Specialist', 'National Healthcareer Association', 'https://www.nhanow.com/', 'NHA credential for professionals demonstrating competency in medical billing and coding fundamentals.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Billing and Administrative (NHA)'), -- 70113
  (70114, 'CEHRS', 'CEHRS', 'Certified Electronic Health Records Specialist', 'National Healthcareer Association', 'https://www.nhanow.com/', 'NHA credential for professionals who manage and work with electronic health record systems in clinical and administrative settings.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Billing and Administrative (NHA)'), -- 70114
  (70115, 'CMAA', 'CMAA', 'Certified Medical Administrative Assistant', 'National Healthcareer Association', 'https://www.nhanow.com/', 'NHA credential for medical administrative assistants demonstrating skills in scheduling, billing, and patient communication.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Billing and Administrative (NHA)'), -- 70115

  -- Healthcare Audit and Integrity
  (70116, 'CHIAP', 'CHIAP', 'Certified Healthcare Internal Audit Professional', 'Association of Healthcare Internal Auditors', 'https://ahia.org/about-chiap-certification/', 'AHIA credential for internal audit professionals specializing in healthcare organization auditing, compliance, and risk assessment.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Audit and Integrity'), -- 70116
  (70117, 'CHBME', 'CHBME', 'Certified Healthcare Business Management Executive', 'Healthcare Business Management Association', 'https://www.hbma.org/content/services/chbme-individual-certification', 'HBMA credential for executives in healthcare billing and revenue cycle management organizations.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Audit and Integrity'), -- 70117

  -- Healthcare Ethics
  (70118, 'HEC-C', 'HEC-C', 'Healthcare Ethics Consultant-Certified', 'American Society for Bioethics and Humanities', 'https://asbh.org/certification/hcec-certification', 'ASBH credential for healthcare ethics consultants demonstrating competency in clinical ethics consultation, policy review, and ethics education.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Healthcare Ethics'), -- 70118

  -- Health Unit Coordination
  (70119, 'CHUC', 'CHUC', 'Certified Health Unit Coordinator', 'National Association of Health Unit Coordinators', 'https://nahuc.org/532-2/current-certified-health-unit-coordinators/', 'NAHUC credential for health unit coordinators who manage patient care coordination, communication, and clerical functions on patient care units.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Health Unit Coordination'), -- 70119

  -- Medical Imaging Informatics
  (70120, 'CIIP', 'CIIP', 'Certified Imaging Informatics Professional', 'American Board of Imaging Informatics', 'https://www.abii.org/', 'ABII credential for professionals at the intersection of medical imaging and information technology in radiology and healthcare systems.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Medical Imaging Informatics'), -- 70120

  -- Oncology Data
  (70121, 'ODS', 'ODS', 'Oncology Data Specialist', 'National Cancer Registrars Association', 'https://www.ncra-usa.org/ctr', 'NCRA credential for cancer registrars and oncology data specialists who collect, manage, and analyze cancer data for research and quality improvement.', FALSE, FALSE, TRUE, FALSE, FALSE, 0, NULL, NULL, 'Oncology Data'), -- 70121

  -- HIMSS Fellowship
  (70122, 'FHIMSS', 'FHIMSS', 'Fellow Member of the Healthcare Information and Management Systems Society', 'HIMSS', 'https://www.himss.org/networking/member-advancement/', 'Honorary HIMSS fellowship recognizing distinguished contributions to the advancement of health information and management systems.', FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, NULL, 'HIMSS Fellowship'); -- 70122
